# Generated by Django 5.2.6 on 2026-01-05 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('shops', '0008_writeoffreason_stocktake_stocktakeline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageOpeningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено')),
                ('main_office_filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offices.mainofficefilial', verbose_name='Филиал ГК')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Запрос на открытие ТТ/хранилища',
                'verbose_name_plural': 'Запросы на открытие ТТ/хранилища',
            },
        ),
    ]
