# Generated by Django 5.2.6 on 2026-01-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_storageopeningrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainofficefilial',
            options={'verbose_name': 'Филиал головного офиса', 'verbose_name_plural': 'Филиалы головного офиса'},
        ),
    ]
