# Generated by Django 5.2.6 on 2026-01-04 11:53

import django.db.models.deletion
import shops.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Справочник категорий продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Справочник единиц измерения',
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип хранилища',
                'verbose_name_plural': 'Типы хранилища',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Описание')),
                ('expiration_days', models.PositiveSmallIntegerField(verbose_name='Кол-во дней до истечения срока годности')),
                ('producer_name', models.CharField(max_length=128, verbose_name='Производитель')),
                ('producer_code', models.UUIDField(verbose_name='Код производителя')),
                ('country_name', models.CharField(max_length=64, verbose_name='Страна')),
                ('additional_info', models.CharField(max_length=300, verbose_name='Дополнительная информация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.productcategory', verbose_name='Категория продукта')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.productunit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Справочник продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=shops.utils.generate_file_path, verbose_name='Медиа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Медиа для карточки товара',
                'verbose_name_plural': 'Медиа для карточек товаров',
            },
        ),
        migrations.CreateModel(
            name='StorageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес (в кг)')),
                ('temp_min_c', models.SmallIntegerField(verbose_name='Мин. температура (Цельсия)')),
                ('temp_max_c', models.SmallIntegerField(verbose_name='Макс. температура (Цельсия)')),
                ('light_sensitive', models.BooleanField(default=False, verbose_name='Чувствителен к свету')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_profiles', to='shops.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Требуемое условие хранения продукта',
                'verbose_name_plural': 'Требуемые условия хранения продуктов',
                'ordering': ['dt_created'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cadastral_number', models.CharField(max_length=20, unique=True, verbose_name='Кадастровый номер')),
                ('approved_by_main_company', models.BooleanField(default=False, verbose_name='Подтверждено ГК')),
                ('opened', models.BooleanField(default=False, verbose_name='Действующий')),
                ('area', models.PositiveSmallIntegerField(verbose_name='Площадь (в кв. м.)')),
                ('utilization_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент утилизации')),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('main_office_filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storages', to='offices.mainofficefilial', verbose_name='Филиал ГК')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storagetype', verbose_name='Тип хранилища')),
            ],
            options={
                'verbose_name': 'Хранилище',
                'verbose_name_plural': 'Хранилища',
                'ordering': ['dt_created'],
            },
        ),
    ]
