# Generated by Django 5.2.6 on 2026-01-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('supplies', '0002_supplycontract_supply_supplycontractproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовления')),
                ('expiry_date', models.DateField(verbose_name='Дата истечения срока годности')),
                ('barcode', models.UUIDField(verbose_name='Штрих-код')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='shops.product', verbose_name='Продукт')),
                ('supply_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplyproduct', verbose_name='Продукт в поставке')),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
            },
        ),
    ]
