# Generated by Django 5.2.6 on 2026-01-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_productinventorylot'),
        ('supplies', '0002_supplycontract_supply_supplycontractproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип перемещения партии',
                'verbose_name_plural': 'Типы перемещения партии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип прайс-листа',
                'verbose_name_plural': 'Типы прайс-листов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип прайс-листа',
                'verbose_name_plural': 'Типы прайс-листов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип места хранения',
                'verbose_name_plural': 'Типы мест хранения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='storagetype',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовления')),
                ('expiry_date', models.DateField(verbose_name='Дата истечения срока годности')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('supply_product_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplyproductlot', verbose_name='Фактическая партия в продуктах поставки')),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.inventorylot', verbose_name='Партия товара')),
            ],
            options={
                'verbose_name': 'Связка партия - место хранения',
                'verbose_name_plural': 'Связки партия - место хранения',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('received_at', models.DateTimeField(verbose_name='Время приёмки')),
                ('business_date', models.DateField(verbose_name='День, когда прайс-лист действует')),
                ('status', models.CharField(choices=[('received', 'Принят'), ('validated', 'Проверен'), ('applied', 'Применен'), ('rejected', 'Отклонен')], default='received', max_length=20, verbose_name='Статус')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('input_cost_vh', models.PositiveSmallIntegerField(verbose_name='Входная цена (ВХ)')),
                ('final_price', models.PositiveSmallIntegerField(verbose_name='Итоговая цена')),
                ('regular_price', models.PositiveSmallIntegerField(verbose_name='Регулярная цена')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_in_price_list', to='shops.pricelist', verbose_name='Прайс-лист')),
                ('price_list_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.pricelistbase', verbose_name='Основание формирования прайс-листа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('price_list_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricelisttype', verbose_name='Тип прайс-листа')),
            ],
            options={
                'verbose_name': 'Прайс-лист для продукта в хранилище',
                'verbose_name_plural': 'Прайс-листы для продуктов в хранилищах',
            },
        ),
        migrations.CreateModel(
            name='PricingConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('scope', models.CharField(choices=[('global', 'Глобально'), ('storage', 'В рамках хранилища'), ('category', 'В рамках категории продукта'), ('product', 'В рамках продукта')], default='global', max_length=20, verbose_name='Область действия')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Приоритет (при пересечениях в scope)')),
                ('max_daily_change_pct', models.PositiveSmallIntegerField(default=90, verbose_name='Макс. изменение цены за день (в процентах)')),
                ('max_markup_pct', models.PositiveSmallIntegerField(default=1000, verbose_name='Макс. наценка (в процентах)')),
                ('product', models.ForeignKey(blank=True, help_text='Указать, если ограничение устанавливается на конкретный продукт', null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('product_category', models.ForeignKey(blank=True, help_text='Указать, если ограничение устанавливается на категорию продуктов', null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.productcategory', verbose_name='Категория продуктов')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_constraints', to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Ограничение на изменение цены',
                'verbose_name_plural': 'Ограничения на изменение цены',
            },
        ),
        migrations.CreateModel(
            name='PricingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('started', 'Запущено'), ('completed', 'Завершено'), ('confirmed', 'Подтверждено'), ('failed', 'Ошибка')], default='started', max_length=20, verbose_name='Статус')),
                ('business_date', models.DateField(verbose_name='Дата, когда приказ действует')),
                ('started_at', models.DateTimeField(verbose_name='Время начала действия')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания действия')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения')),
                ('error_message', models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст ошибки')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Приказ на формирование цен в хранилище',
                'verbose_name_plural': 'Приказы на формирование цен в хранилищах',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('temp_min_c', models.SmallIntegerField(verbose_name='Мин. температура (Цельсия)')),
                ('temp_max_c', models.SmallIntegerField(verbose_name='Макс. температура (Цельсия)')),
                ('max_load', models.PositiveSmallIntegerField(verbose_name='Макс. загрузка (кг)')),
                ('parent_space', models.ForeignKey(help_text='Для иерархии, например, при SALES_AREA', on_delete=django.db.models.deletion.PROTECT, to='shops.space', verbose_name='Родительское место хранения')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_spaces', to='shops.storage', verbose_name='Хранилище')),
                ('space_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.spacetype', verbose_name='Тип хранилища')),
            ],
            options={
                'verbose_name': 'Место хранения в хранилище',
                'verbose_name_plural': 'Места хранения в хранилищах',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.inventorylot', verbose_name='Партия товара')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplies.supply', verbose_name='Поставка')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.movementtype', verbose_name='Тип перемещения')),
                ('space_from', models.ForeignKey(blank=True, help_text='Пустое, если поставка', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='shops.space', verbose_name='Место хранения, из которого совершено перемещение')),
                ('space_to', models.ForeignKey(blank=True, help_text='Пустое, если продажа или кража', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='shops.space', verbose_name='Место хранения, в которое совершено перемещение')),
            ],
            options={
                'verbose_name': 'Перемещение партии по хранилищу',
                'verbose_name_plural': 'Перемещения партий по хранилищам',
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='inventory_lots', through='shops.InventoryBalance', to='shops.space', verbose_name='Места хранения'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.space', verbose_name='Место хранения'),
        ),
        migrations.CreateModel(
            name='StorePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('final_price', models.PositiveSmallIntegerField(verbose_name='Окончательная цена')),
                ('is_sale_allowed', models.BooleanField(default=True, verbose_name='Разрешена ли продажа')),
                ('block_reason', models.CharField(blank=True, default='', verbose_name='Причина блокировки')),
                ('price_list_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricelistbase', verbose_name='Основание формирования прайс-листа')),
                ('price_list_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricelisttype', verbose_name='Тип прайс-листа')),
                ('pricing_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricingrun', verbose_name='Приказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Цена хранилища на день',
                'verbose_name_plural': 'Цена хранилища на день',
            },
        ),
    ]
