# Generated by Django 5.2.6 on 2026-01-05 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_movementtype_pricelistbase_pricelisttype_spacetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprice',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата, когда приказ действует'),
        ),
    ]
