# Generated by Django 5.2.6 on 2026-01-05 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_timeentry_work_type_delete_timeworktype'),
        ('shops', '0004_storeprice_business_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип скидки в купоне',
                'verbose_name_plural': 'Типы скидок в купонах',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='pricelistbase',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='pricingconstraint',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Размер скидки')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
                ('valid_to', models.DateField(verbose_name='Дата окончания действия')),
                ('min_quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мин. кол-во в чеке для применения скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.coupondiscounttype', verbose_name='Тип скидки')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='SaleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Создан'), ('paid', 'Оплачен'), ('canceled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(verbose_name='Время создания')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('total_gross', models.PositiveSmallIntegerField(verbose_name='Полная цена')),
                ('total_discount', models.PositiveSmallIntegerField(verbose_name='Размер скидки')),
                ('total_payable', models.PositiveSmallIntegerField(verbose_name='Цена к оплате')),
                ('paid_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оплаченная сумма')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Время оплаты')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.paymentmethod', verbose_name='Тип оплаты')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='shops.storage', verbose_name='Хранилище')),
                ('time_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_session_receipts', to='employees.timesession', verbose_name='Рабочая сессия')),
            ],
            options={
                'verbose_name': 'Чек продажи',
                'verbose_name_plural': 'Чеки продажи',
            },
        ),
        migrations.CreateModel(
            name='SalesReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во')),
                ('unit_price', models.PositiveSmallIntegerField(verbose_name='Цена единицы')),
                ('line_discount', models.PositiveSmallIntegerField(verbose_name='Суммарная скидка')),
                ('line_total', models.PositiveSmallIntegerField(verbose_name='Итоговая сумма')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.coupon', verbose_name='Купон')),
                ('inventory_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.inventorylot', verbose_name='Партия товара')),
                ('price_list_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.pricelistbase', verbose_name='Основание формирования прайс-листа')),
                ('price_list_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricelisttype', verbose_name='Тип прайс-листа')),
                ('sale_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.salereceipt', verbose_name='Чек продажи')),
            ],
            options={
                'verbose_name': 'Связка чеки - товары',
                'verbose_name_plural': 'Связки чеки - товары',
            },
        ),
        migrations.AddField(
            model_name='salereceipt',
            name='inventory_lots',
            field=models.ManyToManyField(blank=True, related_name='sale_receipts', through='shops.SalesReceiptLine', to='shops.inventorylot', verbose_name='Партии товара'),
        ),
    ]
