# Generated by Django 5.2.6 on 2026-01-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_coupondiscounttype_paymentmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StopListReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина переноса в стоп-лист',
                'verbose_name_plural': 'Причины переноса в стоп-лист',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('business_date', models.DateField(verbose_name='Дата действия')),
                ('status', models.CharField(choices=[('draft', 'Создан'), ('generated', 'Сформирован'), ('sent_to_hq', 'Отправлен в ГК'), ('confirmed', 'Подтвержден'), ('rejected', 'Отказан'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус')),
                ('sent_to_hq_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки в ГК')),
                ('hq_comment', models.CharField(blank=True, default='', verbose_name='Комментарий для ГК')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('pricing_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricingrun', verbose_name='Приказ на формирование цен в хранилище')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Стоп-лист',
                'verbose_name_plural': 'Стоп-листы',
            },
        ),
        migrations.CreateModel(
            name='StopListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('sent_to_hq', 'Отправлен в ГК'), ('hq_replied', 'Получен ответ от ГК'), ('resolved', 'Решен'), ('ignored', 'Проигнорирован')], default='open', max_length=20, verbose_name='Статус')),
                ('input_cost_vh', models.PositiveSmallIntegerField(verbose_name='Входная цена')),
                ('yesterday_price', models.PositiveSmallIntegerField(verbose_name='Вчерашняя цена')),
                ('candidate_price', models.PositiveSmallIntegerField(verbose_name='Минимальная найденная итоговая цена до ограничений')),
                ('final_price_applied', models.PositiveSmallIntegerField(verbose_name='Финальная примененная цена')),
                ('price_list_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.pricelistbase', verbose_name='Основание формирования прайс-листа')),
                ('price_list_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.pricelisttype', verbose_name='Тип прайс-листа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('stop_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.stoplist', verbose_name='Стоп-лист')),
                ('stop_list_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.stoplistreason', verbose_name='Причина попадания в стоп-лист')),
            ],
            options={
                'verbose_name': 'Продукт в стоп-листе',
                'verbose_name_plural': 'Продукты в стоп-листах',
            },
        ),
    ]
