# Generated by Django 5.2.6 on 2026-01-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_stoplistreason_stoplist_stoplistproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип инвентаризации',
                'verbose_name_plural': 'Типы инвентаризации',
                'ordering': ['name'],
            },
        ),
    ]
