# Generated by Django 5.2.6 on 2026-01-05 18:06

import django.db.models.deletion
import django.utils.timezone
import shops.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_stocktaketype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteoffReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='Требует фото')),
            ],
            options={
                'verbose_name': 'Причина списания',
                'verbose_name_plural': 'Причины списания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Создано'), ('in_progress', 'Идет подсчет'), ('submitted', 'Передано директору'), ('returned', 'На доработку'), ('approved', 'Утверждено директором'), ('applied', 'Применены корректировки'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('business_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата учёта')),
                ('snapshot_at', models.DateTimeField(verbose_name='Время снимка учтенных остатков')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения директором')),
                ('director_comment', models.CharField(blank=True, default='', verbose_name='Комментарий директора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время проведения')),
                ('reviewer_comment', models.CharField(blank=True, default='', verbose_name='Комментарий инвентаризатора')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия инвентаризации')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktypes_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktypes_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Кем проведено')),
                ('space', models.ForeignKey(blank=True, help_text='Если пустое, то областью инвентаризации является все хранилище storage', null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.space', verbose_name='Место')),
                ('stocktake_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.stocktaketype', verbose_name='Тип инвентаризации')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('counted_at', models.DateTimeField(verbose_name='Время подсчета')),
                ('quantity_expected', models.PositiveSmallIntegerField(verbose_name='Ожидаемое кол-во')),
                ('quantity_actual', models.PositiveSmallIntegerField(verbose_name='Фактическое кол-во')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Истек срок годности на текущий момент')),
                ('comment', models.CharField(blank=True, default='', verbose_name='Комментарий')),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем подсчитано')),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.inventorylot', verbose_name='Партия')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.space', verbose_name='Место')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.stocktake', verbose_name='Инвентаризация')),
            ],
            options={
                'verbose_name': 'Связь инвентаризация - партия',
                'verbose_name_plural': 'Связи инвентаризация - партия',
            },
        ),
        migrations.CreateModel(
            name='StockTakeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inventory_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.inventorymovement', verbose_name='Перемещение партии по хранилищу')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.stocktake', verbose_name='Инвентаризация')),
                ('stocktake_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.stocktakeline', verbose_name='Связь инвентаризации и партии')),
            ],
            options={
                'verbose_name': 'Связь инвентаризация - движения партий',
            },
        ),
        migrations.AddField(
            model_name='stocktake',
            name='inventory_lots',
            field=models.ManyToManyField(blank=True, through='shops.StockTakeLine', to='shops.inventorylot', verbose_name='Партии товара'),
        ),
        migrations.CreateModel(
            name='WriteOffAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Создан'), ('sent_to_director', 'Отправлено директору на утверждение'), ('returned', 'Возвращено на доработку'), ('approved', 'Утверждено директором'), ('rejected', 'Отклонено директором'), ('posted', 'Проведено'), ('canceled', 'Отменено')], max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения')),
                ('submit_comment', models.CharField(blank=True, default='', verbose_name='Комментарий при подтверждении')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время проведения')),
                ('review_comment', models.CharField(blank=True, default='', verbose_name='Комментарий при проведении')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время списания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_writeoff_acts', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_writeoff_acts', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверен')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_acts', to='shops.storage', verbose_name='Хранилище')),
                ('writeoff_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.writeoffreason', verbose_name='Причина списания')),
            ],
            options={
                'verbose_name': 'Акт списания',
                'verbose_name_plural': 'Акты списания',
            },
        ),
        migrations.CreateModel(
            name='WriteoffAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=shops.utils.generate_file_path_for_writeoff, verbose_name='Изображение')),
                ('writeoff_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='shops.writeoffact', verbose_name='Акт списания')),
            ],
            options={
                'verbose_name': 'Вложение к акту списания',
                'verbose_name_plural': 'Вложения к актам списания',
            },
        ),
        migrations.CreateModel(
            name='WriteoffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во')),
                ('comment', models.CharField(blank=True, default='', verbose_name='Комментарий')),
                ('inventory_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.inventorylot', verbose_name='Партия товара')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.space', verbose_name='Место')),
                ('writeoff_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.writeoffact', verbose_name='Акт списания')),
            ],
            options={
                'verbose_name': 'Строка документа списания',
                'verbose_name_plural': 'Строки документов списания',
            },
        ),
        migrations.CreateModel(
            name='WriteoffPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inventory_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.inventorymovement', verbose_name='Перемещение партии по хранилищу')),
                ('writeoff_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.writeoffact', verbose_name='Акт списания')),
                ('writeoff_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.writeoffline', verbose_name='Строка документа списания')),
            ],
            options={
                'verbose_name': 'Связь акта списания с движениями партий для списания',
                'verbose_name_plural': 'Связи акта списания с движениями партий для списания',
            },
        ),
    ]
