# Generated by Django 5.2.6 on 2026-01-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_writeoffreason_stocktake_stocktakeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='sales_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.salereceipt', verbose_name=''),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='writeoff_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.writeoffact', verbose_name='Акт списания'),
        ),
    ]
