# Generated by Django 5.2.6 on 2026-01-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_inventorymovement_sales_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='sales_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.salereceipt', verbose_name='Чек товара'),
        ),
    ]
