# Generated by Django 5.2.6 on 2026-01-05 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_inventorymovement_sales_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='business_date',
            field=models.DateField(db_index=True, verbose_name='День, когда прайс-лист действует'),
        ),
        migrations.AlterField(
            model_name='pricingrun',
            name='business_date',
            field=models.DateField(db_index=True, verbose_name='Дата, когда приказ действует'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='productinventorylot',
            name='manufacture_date',
            field=models.DateField(db_index=True, verbose_name='Дата изготовления'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='business_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата учёта'),
        ),
        migrations.AlterField(
            model_name='stoplist',
            name='business_date',
            field=models.DateField(db_index=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='business_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата, когда приказ действует'),
        ),
    ]
