# Generated by Django 5.2.6 on 2026-01-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_pricelist_business_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='parent_space',
            field=models.ForeignKey(blank=True, help_text='Для иерархии, например, при SALES_AREA', null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.space', verbose_name='Родительское место хранения'),
        ),
    ]
