# Generated by Django 5.2.6 on 2026-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_space_parent_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='ml_service_id',
            field=models.CharField(blank=True, default='', verbose_name='ID хранилища для ml_service'),
        ),
    ]
