# Generated by Django 5.2.6 on 2026-01-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_storage_ml_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='ml_service_category',
            field=models.CharField(blank=True, choices=[('HOBBIES', 'HOBBIES'), ('FOODS', 'FOODS'), ('HOUSEHOLD', 'HOUSEHOLD')], default='', max_length=20, verbose_name='Категория для ml_service'),
        ),
    ]
