# Generated by Django 5.2.6 on 2026-01-03 12:35

import django.db.models.deletion
import employees.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина корректировки',
                'verbose_name_plural': 'Причины корректировки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalTimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('required_minutes', models.PositiveSmallIntegerField(verbose_name='Необходимые минуты')),
                ('cut_off_minute', models.PositiveSmallIntegerField(verbose_name='Отсекаемая минута')),
                ('prompt_wait_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Минуты ожидания')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Единая политика рабочего времени',
                'verbose_name_plural': 'Единые политики рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Справочник должностей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('counts_against_annual', models.BooleanField(default=False, verbose_name='Учитывается в годовом исчислении')),
                ('requires_documents', models.BooleanField(default=False, verbose_name='Требует документы')),
                ('documents_due_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сроки сдачи документов')),
            ],
            options={
                'verbose_name': 'Тип запроса на временное отсутствие',
                'verbose_name_plural': 'Типы запросов на временное отсутствие',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSessionCloseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина закрытия рабочей сессии',
                'verbose_name_plural': 'Причины закрытия рабочей сессии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип работ для списания времени',
                'verbose_name_plural': 'Типы работ для списания времени',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('monthly_output', models.PositiveSmallIntegerField(verbose_name='Рабочая выработка (в часах)')),
            ],
            options={
                'verbose_name': 'Рабочая ставка',
                'verbose_name_plural': 'Справочник рабочих ставок',
            },
        ),
        migrations.CreateModel(
            name='AnnualLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год')),
                ('base_days', models.PositiveSmallIntegerField(default=28, verbose_name='Число дней отпуска')),
                ('carry_in_days', models.PositiveSmallIntegerField(default=0, verbose_name='Переноска в дни')),
                ('manual_adjust_days', models.PositiveSmallIntegerField(default=0, verbose_name='Ручная корректировка дней')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Отпускной баланс по годам',
                'verbose_name_plural': 'Отпускные балансы по годам',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('on_approval', 'На согласовании'), ('rejected', 'Отказано'), ('planned', 'Запланировано'), ('completed', 'Выполнено')], db_index=True, max_length=30, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('documents_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Документы были предоставлены в')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Пустое, если запрос не одобрен', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, одобривший запрос')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Запрос на временное отсутствие',
                'verbose_name_plural': 'Запросы на временное отсутствие',
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to=employees.utils.generate_file_path, verbose_name='Файл')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='employees.leaverequest', verbose_name='Запрос на временное отсутствие')),
            ],
            options={
                'verbose_name': 'Приложение к запросу на отсутствие',
                'verbose_name_plural': 'Приложения к запросам на отсутствие',
            },
        ),
        migrations.CreateModel(
            name='TimeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('adjusted_minutes', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Скорректированные минуты')),
                ('adjustment_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.adjustmentreason', verbose_name='Причина корректировки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_days', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Сводка по дню сотрудника',
                'verbose_name_plural': 'Сводки по дням сотрудника',
            },
        ),
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('closed', models.BooleanField(db_index=True, default=False, verbose_name='Закрыта')),
                ('login_at', models.DateTimeField(verbose_name='Время начала')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('close_reason', models.ForeignKey(blank=True, help_text='Заполняется только если сессия была закрыта', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.timesessionclosereason', verbose_name='Причина закрытия сессии')),
            ],
            options={
                'verbose_name': 'Рабочая сессия',
                'verbose_name_plural': 'Рабочие сессии',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('minutes', models.PositiveSmallIntegerField(verbose_name='Минуты')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.timeworktype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Списание времени',
                'verbose_name_plural': 'Списания времени',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Сумма')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.jobposition', verbose_name='Должность')),
                ('working_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.workingrate', verbose_name='Ставка')),
            ],
            options={
                'verbose_name': 'Зарплата на должности',
                'verbose_name_plural': 'Зарплаты на должности',
            },
        ),
    ]
