# Generated by Django 5.2.6 on 2026-01-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_adjustmentreason_globaltimepolicy_jobposition_and_more'),
        ('offices', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('main_office_filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='offices.mainofficefilial', verbose_name='Филиал ГК')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.OneToOneField(blank=True, help_text='Пустое, если работник не работает', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.workplace', verbose_name='Рабочее место'),
        ),
    ]
