# Generated by Django 5.2.6 on 2026-01-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_workplace_employee_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeday',
            name='adjustment_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.timesessionclosereason', verbose_name='Причина корректировки'),
        ),
        migrations.DeleteModel(
            name='AdjustmentReason',
        ),
    ]
