# Generated by Django 5.2.6 on 2026-01-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_timeday_adjustment_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='work_type',
        ),
        migrations.DeleteModel(
            name='TimeWorkType',
        ),
    ]
