# Generated by Django 5.2.6 on 2026-01-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_timeentry_work_type_delete_timeworktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Телефон'),
        ),
    ]
