# Generated by Django 5.2.6 on 2026-01-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
    ]
