# Generated by Django 5.2.6 on 2026-01-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_salary_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='type',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.leaverequesttype', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
