# Generated by Django 5.2.6 on 2026-01-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_leaverequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='working_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.workingrate', verbose_name='Ставка'),
        ),
    ]
