# Generated by Django 5.2.6 on 2026-01-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_adjustmentreason_globaltimepolicy_jobposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancyReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина несоответствия поставки ожиданиям',
                'verbose_name_plural': 'Причины несоответствия поставки ожиданиям',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('checking_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('swift', models.CharField(max_length=11, verbose_name='Swift')),
                ('iban', models.CharField(max_length=34, verbose_name='IBan')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default='', max_length=40, verbose_name='Отчество')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('job_title', models.CharField(max_length=80, verbose_name='Должность')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.passport', verbose_name='Паспорт')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Контактное лицо поставщика',
                'verbose_name_plural': 'Контактные лица поставщиков',
            },
        ),
    ]
