# Generated by Django 5.2.6 on 2026-01-04 13:20

import django.db.models.deletion
import supplies.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('supplies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('expiration_date', models.DateField(verbose_name='Дата истечения договора')),
                ('employee_entered_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, заключивший договор')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='supplies.supplier', verbose_name='Поставщик')),
                ('supplier_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplies.supplycontract', verbose_name='Контактное лицо, заключившее договор')),
            ],
            options={
                'verbose_name': 'Договор на поставки',
                'verbose_name_plural': 'Договора на поставки',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('planned_date', models.DateField(db_index=True, verbose_name='Планируемая дата поставки')),
                ('arrived_at', models.DateTimeField(verbose_name='Время прибытия')),
                ('status', models.CharField(choices=[('draft', 'Создано'), ('in_receiving', 'Кладовщик вводит фактические данные'), ('pending_approval', 'Требует решения товароведа/ГК'), ('approved', 'Разрешено проводить'), ('rejected', 'Отклонено'), ('closed', 'Закрыто')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies_created', to=settings.AUTH_USER_MODEL, verbose_name='Создана сотрудником')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies_received', to=settings.AUTH_USER_MODEL, verbose_name='Принята сотрудником')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.storage', verbose_name='Хранилище')),
                ('supply_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplycontract', verbose_name='Контракт на поставку')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyContractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена (общая)')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во')),
                ('delivery_frequency', models.CharField(choices=[('one_time', 'Единоразово'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в две недели'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('on_demand', 'По требованию')], default='one_time', max_length=20, verbose_name='Частота доставки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('supply_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supplies.supplycontract', verbose_name='Договор на поставку')),
            ],
            options={
                'verbose_name': 'Продукт в договоре на поставку',
                'verbose_name_plural': 'Продукты в договорах на поставки',
            },
        ),
        migrations.CreateModel(
            name='SupplyDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('sent_to_hq', 'Отправлено в ГК'), ('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('resolved', 'Урегулировано')], default='open', max_length=20, verbose_name='Статус')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('decision_comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий к решению')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies_decided', to=settings.AUTH_USER_MODEL, verbose_name='Принято')),
                ('discrepancy_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.discrepancyreason', verbose_name='Причина несоответствия поставки ожиданиям')),
            ],
            options={
                'verbose_name': 'Несоответствие поставки ожиданиям',
                'verbose_name_plural': 'Несоответствия поставок ожиданиям',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to=supplies.utils.generate_file_path, verbose_name='Файл')),
                ('supply_discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='supplies.supplydiscrepancy', verbose_name='Заявка на несоответствие поставки')),
            ],
            options={
                'verbose_name': 'Вложение к заявке на несоответствие поставки',
                'verbose_name_plural': 'Вложения к заявкам на несоответствия поставкам',
            },
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity_actual_total', models.PositiveSmallIntegerField(verbose_name='Сумма по связанным партиям')),
                ('quantity_expected', models.PositiveSmallIntegerField(verbose_name='Ожидаемое кол-во')),
                ('requires_review', models.BooleanField(default=True, verbose_name='Требует осмотра')),
                ('status', models.CharField(choices=[('ok', 'Ок'), ('has_issues', 'Есть несоответствия'), ('resolved', 'Решено')], default='has_issues', max_length=20, verbose_name='Статус')),
                ('purchase_price', models.PositiveSmallIntegerField(verbose_name='Стоимость покупки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.product', verbose_name='Продукт')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supply', verbose_name='Поставка')),
                ('supply_contract_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplycontractproduct', verbose_name='Продукт в поставке')),
            ],
            options={
                'verbose_name': 'Продукт в поставке',
                'verbose_name_plural': 'Продукты в поставке',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='SupplyProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовления')),
                ('expiry_date_actual', models.DateField(verbose_name='Фактическая дата окончания срока годности')),
                ('quantity_actual', models.PositiveSmallIntegerField(verbose_name='Фактическое кол-во')),
                ('packaging_condition', models.CharField(choices=[('ok', 'Ок'), ('damaged', 'Есть повреждения упаковки')], max_length=10, verbose_name='Состояние упаковки')),
                ('status', models.CharField(choices=[('draft', 'Создано'), ('confirmed', 'Подтверждено'), ('on_hold', 'На удержании')], default='draft', max_length=10, verbose_name='Статус')),
                ('supply_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplyproduct', verbose_name='Продукт в поставке')),
            ],
            options={
                'verbose_name': 'Фактическая партия в продуктах поставки',
                'verbose_name_plural': 'Фактические партии в продуктах поставок',
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='supplydiscrepancy',
            name='supply_product_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supplyproductlot', verbose_name='Фактическая партия в продуктах поставки'),
        ),
    ]
